# -*- coding: utf-8 -*-
#====================================================================
#
# Copyright © 2023 China Mobile IOT. All rights reserved.
#
#
#====================================================================


Import('env')
from ModuleBuild import *

module = 'custom_main'  # 模块名，同簇模块不得重名
current_dir = os.path.join(Dir('.').abspath)
target = None


#========================================================
# ram_source_files：运行在ram中
# flash_source_files：运行在flash中
#========================================================
ram_source_files = [
    'custom_main/src/custom_main.c',
    'custom_main/src/app_mode.c',
    'custom_main/src/app_utils.c',
    'custom_main/src/app_mqtt_client.c',
    'custom_main/src/app_protocol.c',
    'custom_main/src/app_command.c',
    'custom_main/src/app_lbs.c',
]

flash_source_files = [
    'custom_main/src/bsp.c',
    'custom_main/src/app_storage.c',
    'custom_main/src/app_provisioning.c',
    'custom_main/src/app_offline_cache.c',
    'custom_main/src/app_ota.c',
]


#========================================================
# public_incs：置于工程环境中，供其他模块引用
# private_incs：仅在本模块中引用
#========================================================
public_incs = [
]

private_incs = [
    current_dir + '/custom_main/inc',
    current_dir + '/../src/modem',
    current_dir + '/../third-party/mbedtls/include',
    current_dir + '/../third-party/cJSONFiles/cJSON',
]


#========================================================
# cpp_define：仅适用于本模块，对其他模块不可见
#========================================================
cpp_defines = [
]


#========================================================
# 模块编译
#========================================================
mod = ModuleBuild(env,
        name = module,
        ram_srcs = ram_source_files,
        flash_srcs = flash_source_files,
        pub_incs = public_incs,
        pri_incs = private_incs,
        cpp_define = cpp_defines
)

target = mod.build_object()

Return('target')
