/*------------------------------------------------------------
(C) Copyright [2006-2008] Marvell International Ltd.
All Rights Reserved
------------------------------------------------------------*/

/*********************************************************************
* Filename:     AUX_TABLE_RxBandZoneToFirstArfcn_CalBody.h
* Created By:   Ilan meltser on 6/18/2008
* Programmers:  Elad Goldman
* Module:       Generic RF Module - Data Base
* RF Type:      SKY_Hel3
* DB Ver.:      0.9
* Doc Ver.:     2.94
* GUI Ver.:     7.26
*
* Description:  Contains the "AUX_TABLE_RxBandZoneToFirstArfcn" CalBody
*
* Notes:        This file is automatically generated by WIZARD.
*********************************************************************/

/*
 * each line in the file contain the data of 1*Int16:
*/
//|-FirstArfcn-------------|-fixedIndex2------------|-fixedIndex1------------|-fixedIndex0------------|
   0,                       // EGSM_BAND,                LNA_ACTIVE,               0,                       
   11,                      // EGSM_BAND,                LNA_ACTIVE,               1,                       
   22,                      // EGSM_BAND,                LNA_ACTIVE,               2,                       
   33,                      // EGSM_BAND,                LNA_ACTIVE,               3,                       
   44,                      // EGSM_BAND,                LNA_ACTIVE,               4,                       
   55,                      // EGSM_BAND,                LNA_ACTIVE,               5,                       
   66,                      // EGSM_BAND,                LNA_ACTIVE,               6,                       
   77,                      // EGSM_BAND,                LNA_ACTIVE,               7,                       
   88,                      // EGSM_BAND,                LNA_ACTIVE,               8,                       
   99,                      // EGSM_BAND,                LNA_ACTIVE,               9,                       
   110,                     // EGSM_BAND,                LNA_ACTIVE,               10,                      
   121,                     // EGSM_BAND,                LNA_ACTIVE,               11,                      
   132,                     // EGSM_BAND,                LNA_ACTIVE,               12,                      
   143,                     // EGSM_BAND,                LNA_ACTIVE,               13,                      
   154,                     // EGSM_BAND,                LNA_ACTIVE,               14,                      
   165,                     // EGSM_BAND,                LNA_ACTIVE,               15,                      

   0,                       // EGSM_BAND,                LNA_BYPASSED,             0,                       
   11,                      // EGSM_BAND,                LNA_BYPASSED,             1,                       
   22,                      // EGSM_BAND,                LNA_BYPASSED,             2,                       
   33,                      // EGSM_BAND,                LNA_BYPASSED,             3,                       
   44,                      // EGSM_BAND,                LNA_BYPASSED,             4,                       
   55,                      // EGSM_BAND,                LNA_BYPASSED,             5,                       
   66,                      // EGSM_BAND,                LNA_BYPASSED,             6,                       
   77,                      // EGSM_BAND,                LNA_BYPASSED,             7,                       
   88,                      // EGSM_BAND,                LNA_BYPASSED,             8,                       
   99,                      // EGSM_BAND,                LNA_BYPASSED,             9,                       
   110,                     // EGSM_BAND,                LNA_BYPASSED,             10,                      
   121,                     // EGSM_BAND,                LNA_BYPASSED,             11,                      
   132,                     // EGSM_BAND,                LNA_BYPASSED,             12,                      
   143,                     // EGSM_BAND,                LNA_BYPASSED,             13,                      
   154,                     // EGSM_BAND,                LNA_BYPASSED,             14,                      
   165,                     // EGSM_BAND,                LNA_BYPASSED,             15,                      

   0,                       // DCS_BAND,                 LNA_ACTIVE,               0,                       
   25,                      // DCS_BAND,                 LNA_ACTIVE,               1,                       
   50,                      // DCS_BAND,                 LNA_ACTIVE,               2,                       
   75,                      // DCS_BAND,                 LNA_ACTIVE,               3,                       
   100,                     // DCS_BAND,                 LNA_ACTIVE,               4,                       
   125,                     // DCS_BAND,                 LNA_ACTIVE,               5,                       
   150,                     // DCS_BAND,                 LNA_ACTIVE,               6,                       
   175,                     // DCS_BAND,                 LNA_ACTIVE,               7,                       
   200,                     // DCS_BAND,                 LNA_ACTIVE,               8,                       
   225,                     // DCS_BAND,                 LNA_ACTIVE,               9,                       
   250,                     // DCS_BAND,                 LNA_ACTIVE,               10,                      
   275,                     // DCS_BAND,                 LNA_ACTIVE,               11,                      
   300,                     // DCS_BAND,                 LNA_ACTIVE,               12,                      
   325,                     // DCS_BAND,                 LNA_ACTIVE,               13,                      
   350,                     // DCS_BAND,                 LNA_ACTIVE,               14,                      
   350,                     // DCS_BAND,                 LNA_ACTIVE,               15,                      

   0,                       // DCS_BAND,                 LNA_BYPASSED,             0,                       
   25,                      // DCS_BAND,                 LNA_BYPASSED,             1,                       
   50,                      // DCS_BAND,                 LNA_BYPASSED,             2,                       
   75,                      // DCS_BAND,                 LNA_BYPASSED,             3,                       
   100,                     // DCS_BAND,                 LNA_BYPASSED,             4,                       
   125,                     // DCS_BAND,                 LNA_BYPASSED,             5,                       
   150,                     // DCS_BAND,                 LNA_BYPASSED,             6,                       
   175,                     // DCS_BAND,                 LNA_BYPASSED,             7,                       
   200,                     // DCS_BAND,                 LNA_BYPASSED,             8,                       
   225,                     // DCS_BAND,                 LNA_BYPASSED,             9,                       
   250,                     // DCS_BAND,                 LNA_BYPASSED,             10,                      
   275,                     // DCS_BAND,                 LNA_BYPASSED,             11,                      
   300,                     // DCS_BAND,                 LNA_BYPASSED,             12,                      
   325,                     // DCS_BAND,                 LNA_BYPASSED,             13,                      
   350,                     // DCS_BAND,                 LNA_BYPASSED,             14,                      
   350,                     // DCS_BAND,                 LNA_BYPASSED,             15,                      

   0,                       // PCS_BAND,                 LNA_ACTIVE,               0,                       
   19,                      // PCS_BAND,                 LNA_ACTIVE,               1,                       
   38,                      // PCS_BAND,                 LNA_ACTIVE,               2,                       
   57,                      // PCS_BAND,                 LNA_ACTIVE,               3,                       
   76,                      // PCS_BAND,                 LNA_ACTIVE,               4,                       
   95,                      // PCS_BAND,                 LNA_ACTIVE,               5,                       
   114,                     // PCS_BAND,                 LNA_ACTIVE,               6,                       
   133,                     // PCS_BAND,                 LNA_ACTIVE,               7,                       
   152,                     // PCS_BAND,                 LNA_ACTIVE,               8,                       
   171,                     // PCS_BAND,                 LNA_ACTIVE,               9,                       
   190,                     // PCS_BAND,                 LNA_ACTIVE,               10,                      
   209,                     // PCS_BAND,                 LNA_ACTIVE,               11,                      
   228,                     // PCS_BAND,                 LNA_ACTIVE,               12,                      
   247,                     // PCS_BAND,                 LNA_ACTIVE,               13,                      
   266,                     // PCS_BAND,                 LNA_ACTIVE,               14,                      
   285,                     // PCS_BAND,                 LNA_ACTIVE,               15,                      

   0,                       // PCS_BAND,                 LNA_BYPASSED,             0,                       
   19,                      // PCS_BAND,                 LNA_BYPASSED,             1,                       
   38,                      // PCS_BAND,                 LNA_BYPASSED,             2,                       
   57,                      // PCS_BAND,                 LNA_BYPASSED,             3,                       
   76,                      // PCS_BAND,                 LNA_BYPASSED,             4,                       
   95,                      // PCS_BAND,                 LNA_BYPASSED,             5,                       
   114,                     // PCS_BAND,                 LNA_BYPASSED,             6,                       
   133,                     // PCS_BAND,                 LNA_BYPASSED,             7,                       
   152,                     // PCS_BAND,                 LNA_BYPASSED,             8,                       
   171,                     // PCS_BAND,                 LNA_BYPASSED,             9,                       
   190,                     // PCS_BAND,                 LNA_BYPASSED,             10,                      
   209,                     // PCS_BAND,                 LNA_BYPASSED,             11,                      
   228,                     // PCS_BAND,                 LNA_BYPASSED,             12,                      
   247,                     // PCS_BAND,                 LNA_BYPASSED,             13,                      
   266,                     // PCS_BAND,                 LNA_BYPASSED,             14,                      
   285,                     // PCS_BAND,                 LNA_BYPASSED,             15,                      

   0,                       // GSM_850_BAND,             LNA_ACTIVE,               0,                       
   8,                       // GSM_850_BAND,             LNA_ACTIVE,               1,                       
   16,                      // GSM_850_BAND,             LNA_ACTIVE,               2,                       
   24,                      // GSM_850_BAND,             LNA_ACTIVE,               3,                       
   32,                      // GSM_850_BAND,             LNA_ACTIVE,               4,                       
   40,                      // GSM_850_BAND,             LNA_ACTIVE,               5,                       
   48,                      // GSM_850_BAND,             LNA_ACTIVE,               6,                       
   56,                      // GSM_850_BAND,             LNA_ACTIVE,               7,                       
   64,                      // GSM_850_BAND,             LNA_ACTIVE,               8,                       
   72,                      // GSM_850_BAND,             LNA_ACTIVE,               9,                       
   80,                      // GSM_850_BAND,             LNA_ACTIVE,               10,                      
   88,                      // GSM_850_BAND,             LNA_ACTIVE,               11,                      
   96,                      // GSM_850_BAND,             LNA_ACTIVE,               12,                      
   104,                     // GSM_850_BAND,             LNA_ACTIVE,               13,                      
   112,                     // GSM_850_BAND,             LNA_ACTIVE,               14,                      
   65535,                   // GSM_850_BAND,             LNA_ACTIVE,               15,                      

   0,                       // GSM_850_BAND,             LNA_BYPASSED,             0,                       
   8,                       // GSM_850_BAND,             LNA_BYPASSED,             1,                       
   16,                      // GSM_850_BAND,             LNA_BYPASSED,             2,                       
   24,                      // GSM_850_BAND,             LNA_BYPASSED,             3,                       
   32,                      // GSM_850_BAND,             LNA_BYPASSED,             4,                       
   40,                      // GSM_850_BAND,             LNA_BYPASSED,             5,                       
   48,                      // GSM_850_BAND,             LNA_BYPASSED,             6,                       
   56,                      // GSM_850_BAND,             LNA_BYPASSED,             7,                       
   64,                      // GSM_850_BAND,             LNA_BYPASSED,             8,                       
   72,                      // GSM_850_BAND,             LNA_BYPASSED,             9,                       
   80,                      // GSM_850_BAND,             LNA_BYPASSED,             10,                      
   88,                      // GSM_850_BAND,             LNA_BYPASSED,             11,                      
   96,                      // GSM_850_BAND,             LNA_BYPASSED,             12,                      
   104,                     // GSM_850_BAND,             LNA_BYPASSED,             13,                      
   112,                     // GSM_850_BAND,             LNA_BYPASSED,             14,                      
   65535,                   // GSM_850_BAND,             LNA_BYPASSED,             15,                      

