/*------------------------------------------------------------
(C) Copyright [2006-2008] Marvell International Ltd.
All Rights Reserved
------------------------------------------------------------*/

/*********************************************************************
* Filename:     AUX_TABLE_RxAgcControlCode_CalBody.h
* Created By:   Ilan meltser on 6/18/2008
* Programmers:  Elad Goldman
* Module:       Generic RF Module - Data Base
* RF Type:      SKY_Hel3
* DB Ver.:      0.9
* Doc Ver.:     2.94
* GUI Ver.:     7.26
*
* Description:  Contains the "AUX_TABLE_RxAgcControlCode" CalBody
*
* Notes:        This file is automatically generated by WIZARD.
*********************************************************************/

/*
 * each line in the file contain the data of 49*Int16:
*/

//	8bit Signed Input Antenna Power Level  2dB step      -14dBm  ~   -110dBm  

//|-GainCode0--------------|-GainCode1--------------|-GainCode2--------------|-GainCode3--------------|-GainCode4--------------|-GainCode5--------------|-GainCode6--------------|-GainCode7--------------|-GainCode8--------------|-GainCode9--------------|-GainCode10-------------|-GainCode11-------------|-GainCode12-------------|-GainCode13-------------|-GainCode14-------------|-GainCode15-------------|-GainCode16-------------|-GainCode17-------------|-GainCode18-------------|-GainCode19-------------|-GainCode20-------------|-GainCode21-------------|-GainCode22-------------|-GainCode23-------------|-GainCode24-------------|-GainCode25-------------|-GainCode26-------------|-GainCode27-------------|-GainCode28-------------|-GainCode29-------------|-GainCode30-------------|-GainCode31-------------|-GainCode32-------------|-GainCode33-------------|-GainCode34-------------|-GainCode35-------------|-GainCode36-------------|-GainCode37-------------|-GainCode38-------------|-GainCode39-------------|-GainCode40-------------|-GainCode41-------------|-GainCode42-------------|-GainCode43-------------|-GainCode44-------------|-GainCode45-------------|-GainCode46-------------|-GainCode47-------------|-GainCode48-------------|-fixedIndex0------------|
      0xF2,                  0xF0,                   0xEE,                    0xEC,                    0xEA,                    0xE8,                    0xE6,                    0xE4,                    0xE2,                    0xE0,                    0xDE,                    0xDC,                    0xDA,                    0xD8,                    0xD6,                    0xD4,                    0xD2,                    0xD0,                    0xCE,                    0xCC,                    0xCA,                    0xC8,                    0xC6,                    0xC4,                     0xC2,                     0xC0,                     0xBE,                     0xBC,                     0xBA,                  0xB8,                     0xB6,                     0xB4,                     0xB2,                  0xB0,                    0xAE,                    0xAC,                    0xAA,                    0xA8,                    0xA6,                    0xA4,                    0xA2,                    0xA0,                    0x9E,                    0x9C,                    0x9A,                    0x98,                    0x96,                    0x94,                    0x92,                    // EGSM_BAND,               
      0xF2,					 0xF0,					 0xEE,					  0xEC, 				   0xEA,					0xE8,					 0xE6,					  0xE4, 				   0xE2,					0xE0,					 0xDE,					  0xDC, 				   0xDA,					0xD8,					 0xD6,					  0xD4, 				   0xD2,					0xD0,					 0xCE,					  0xCC, 				   0xCA,					0xC8,					 0xC6,					  0xC4, 					0xC2,					  0xC0, 					0xBE,					  0xBC, 					0xBA,				   0xB8,					 0xB6,					   0xB4,					 0xB2,					0xB0,					 0xAE,					  0xAC, 				   0xAA,					0xA8,					 0xA6,					  0xA4, 				   0xA2,					0xA0,					 0x9E,					  0x9C, 				   0x9A,					0x98,					 0x96,					  0x94, 				   0x92,					// DCS_BAND,				
      0xF2,					 0xF0,					 0xEE,					  0xEC, 				   0xEA,					0xE8,					 0xE6,					  0xE4, 				   0xE2,					0xE0,					 0xDE,					  0xDC, 				   0xDA,					0xD8,					 0xD6,					  0xD4, 				   0xD2,					0xD0,					 0xCE,					  0xCC, 				   0xCA,					0xC8,					 0xC6,					  0xC4, 					0xC2,					  0xC0, 					0xBE,					  0xBC, 					0xBA,				   0xB8,					 0xB6,					   0xB4,					 0xB2,					0xB0,					 0xAE,					  0xAC, 				   0xAA,					0xA8,					 0xA6,					  0xA4, 				   0xA2,					0xA0,					 0x9E,					  0x9C, 				   0x9A,					0x98,					 0x96,					  0x94, 				   0x92,					// PCS_BAND,				
      0xF2,					 0xF0,					 0xEE,					  0xEC, 				   0xEA,					0xE8,					 0xE6,					  0xE4, 				   0xE2,					0xE0,					 0xDE,					  0xDC, 				   0xDA,					0xD8,					 0xD6,					  0xD4, 				   0xD2,					0xD0,					 0xCE,					  0xCC, 				   0xCA,					0xC8,					 0xC6,					  0xC4, 					0xC2,					  0xC0, 					0xBE,					  0xBC, 					0xBA,				   0xB8,					 0xB6,					   0xB4,					 0xB2,					0xB0,					 0xAE,					  0xAC, 				   0xAA,					0xA8,					 0xA6,					  0xA4, 				   0xA2,					0xA0,					 0x9E,					  0x9C, 				   0x9A,					0x98,					 0x96,					  0x94, 				   0x92,					// GSM_850_BAND,				     
