#ifdef VOICE_ECALL_BUILD

#ifndef ECALL_ERROR_ID_H_
#define ECALL_ERROR_ID_H_

#define COM_WARNING_ID_VOICE_ECALL_ABORT_UNEXPECTEDLY    0x00002504 
#define COM_WARNING_ID_VOICE_ECALL_UNKNOWN_IPC_CMD   	 0x00002502 
#define COM_WARNING_ID_VOICE_ECALL_UNKNOWN_IVS_EVENT  0x00002503 
#define COM_WARNING_ID_VOICE_ECALL_WRONG_MSD_LENGTH  0x00002505 
#define COM_WARNING_ID_VOICE_ECALL_WRONG_TEST_DATA    0x00002506   
#endif //ECALL_ERROR_ID_H_

#endif //VOICE_ECALL_BUILD
