/*------------------------------------------------------------
(C) Copyright [2006-2008] Marvell International Ltd.
All Rights Reserved
------------------------------------------------------------*/

/*********************************************************************
* Filename:     AUX_TABLE_RxAgcParameters_CalBody.h
* Created By:   Ilan meltser on 6/18/2008
* Programmers:  Elad Goldman
* Module:       Generic RF Module - Data Base
* RF Type:      SKY_Hel3
* DB Ver.:      0.9
* Doc Ver.:     2.94
* GUI Ver.:     7.26
*
* Description:  Contains the "AUX_TABLE_RxAgcParameters" CalBody
*
* Notes:        This file is automatically generated by WIZARD.
*********************************************************************/

/*
 * each line in the file contain the data of 3*Int16:
*/
//|-TempZoneSize-----------|-MinTemperature---------|-MaxTemperature---------|-fixedIndex0------------|
   25,                      243,                     343,                     // EGSM_BAND,               
   25,                      243,                     343,                     // DCS_BAND,                
   25,                      243,                     343,                     // PCS_BAND,                
   25,                      243,                     343,                     // GSM_850_BAND,            
