/*------------------------------------------------------------
(C) Copyright [2006-2008] Marvell International Ltd.
All Rights Reserved
------------------------------------------------------------*/

/*********************************************************************
* Filename:     AUX_TABLE_RxSelfCalResults_CalBody.h
* Created By:   Ilan meltser on 6/18/2008
* Programmers:  Elad Goldman
* Module:       Generic RF Module - Data Base
* RF Type:      SKY_Hel3
* DB Ver.:      0.9
* Doc Ver.:     2.94
* GUI Ver.:     7.26
*
* Description:  Contains the "AUX_TABLE_RxSelfCalResults" CalBody
*
* Notes:        This file is automatically generated by WIZARD.
*********************************************************************/

/*
 * each line in the file contain the data of 1*Int32:
*/
//|-Rx_SC_Result0-----------|-Rx_SC_Result1-----------|-Rx_SC_Result2-----------|-Rx_SC_Result3-----------|-Rx_SC_Result4-----------|-Rx_SC_Result5-----------|-Rx_SC_Result6-----------|-Rx_SC_Result7-----------|-Rx_SC_Result8-----------|-Rx_SC_Result9-----------|-Rx_SC_Result10----------|-Rx_SC_Result11----------|-Rx_SC_Result12----------|-Rx_SC_Result13----------|-Rx_SC_Result14----------|-Rx_SC_Result15----------|-fixedIndex0------------|
   0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        // EGSM_BAND,
   0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        // DCS_BAND,
   0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        // PCS_BAND,
   0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0,                        0                         // GSM_850_BAND
