/*------------------------------------------------------------
(C) Copyright [2006-2008] Marvell International Ltd.
All Rights Reserved
------------------------------------------------------------*/

/*********************************************************************
* Filename:     AUX_TABLE_RxAgcAccurateGain_CalBody.h
* Created By:   Ilan meltser on 6/18/2008
* Programmers:  Elad Goldman
* Module:       Generic RF Module - Data Base
* RF Type:      SKY_Hel3
* DB Ver.:      0.9
* Doc Ver.:     2.94
* GUI Ver.:     7.26
*
* Description:  Contains the "AUX_TABLE_RxAgcAccurateGain" CalBody
*
* Notes:        This file is automatically generated by WIZARD.
*********************************************************************/

/*
 * each line in the file contain the data of 49*Int16:
*/
//|-AccurateGain0----------|-AccurateGain1----------|-AccurateGain2----------|-AccurateGain3----------|-AccurateGain4----------|-AccurateGain5----------|-AccurateGain6----------|-AccurateGain7----------|-AccurateGain8----------|-AccurateGain9----------|-AccurateGain10---------|-AccurateGain11---------|-AccurateGain12---------|-AccurateGain13---------|-AccurateGain14---------|-AccurateGain15---------|-AccurateGain16---------|-AccurateGain17---------|-AccurateGain18---------|-AccurateGain19---------|-AccurateGain20---------|-AccurateGain21---------|-AccurateGain22---------|-AccurateGain23---------|-AccurateGain24---------|-AccurateGain25---------|-AccurateGain26---------|-AccurateGain27---------|-AccurateGain28---------|-AccurateGain29---------|-AccurateGain30---------|-AccurateGain31---------|-AccurateGain32---------|-AccurateGain33---------|-AccurateGain34---------|-AccurateGain35---------|-AccurateGain36---------|-AccurateGain37---------|-AccurateGain38---------|-AccurateGain39---------|-AccurateGain40---------|-AccurateGain41---------|-AccurateGain42---------|-AccurateGain43---------|-AccurateGain44---------|-AccurateGain45---------|-AccurateGain46---------|-AccurateGain47---------|-AccurateGain48---------|-fixedIndex0------------|
		
    1150,     1172,     1198,     1225,     1256,     1285,     1314,     1347,     1373,     1404,     1435,     1466,     1496,     1527,     1558,     1589,     1622,     1654,     1686,     1720,     1748,     1783,     1821,     1853,     1884,     1915,     1946,     1980,     2011,     2042,     2072,     2107,     2137,     2169,     2203,     2234,     2266,     2296,     2326,     2360,     2391,     2423,     2453,     2487,     2521,     2555,     2586,     2624,     2663,      
    1114,     1144,     1178,     1212,     1242,     1276,     1306,     1336,     1350,     1384,     1412,     1446,     1478,     1507,     1538,     1570,     1603,     1635,     1666,     1697,     1729,     1761,     1794,     1827,     1857,     1889,     1922,     1952,     1983,     2013,     2044,     2079,     2109,     2143,     2177,     2209,     2240,     2272,     2301,     2332,     2363,     2397,     2427,     2463,     2503,     2545,     2578,     2631,     2677,      
    1096,     1126,     1158,     1192,     1223,     1257,     1286,     1315,     1356,     1390,     1419,     1453,     1498,     1529,     1560,     1591,     1624,     1655,     1686,     1718,     1749,     1780,     1809,     1841,     1870,     1903,     1937,     1967,     1997,     2028,     2059,     2093,     2124,     2158,     2193,     2223,     2254,     2285,     2317,     2349,     2379,     2413,     2448,     2477,     2510,     2544,     2583,     2628,     2674,      
    1081,     1107,     1136,     1165,     1197,     1227,     1257,     1291,     1324,     1355,     1386,     1417,     1446,     1477,     1509,     1540,     1577,     1610,     1641,     1676,     1704,     1738,     1777,     1808,     1839,     1870,     1902,     1937,     1977,     2007,     2038,     2073,     2103,     2135,     2169,     2200,     2231,     2263,     2290,     2324,     2353,     2386,     2420,     2452,     2486,     2517,     2554,     2584,     2627,      
					
					
				
		
